"""empty message

Revision ID: 2286777c5054
Revises: b08970b01926
Create Date: 2016-10-02 21:55:01.409434

"""

# revision identifiers, used by Alembic.
revision = '2286777c5054'
down_revision = 'b08970b01926'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('current_login_ip', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'current_login_ip')
    op.drop_column('users', 'current_login_at')
    ### end Alembic commands ###
