"""empty message

Revision ID: 23d186979072
Revises: 2286777c5054
Create Date: 2016-10-04 13:11:01.241664

"""

# revision identifiers, used by Alembic.
revision = '23d186979072'
down_revision = '2286777c5054'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['social_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'social_id')
    op.create_table('connection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'connection_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'connection_pkey')
    )
    ### end Alembic commands ###
