"""empty message

Revision ID: 342e1f36cb5b
Revises: 37579a5ae821
Create Date: 2016-10-08 11:37:04.114112

"""

# revision identifiers, used by Alembic.
revision = '342e1f36cb5b'
down_revision = '37579a5ae821'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    ### end Alembic commands ###
