"""empty message

Revision ID: 37579a5ae821
Revises: 23d186979072
Create Date: 2016-10-08 09:58:20.258768

"""

# revision identifiers, used by Alembic.
revision = '37579a5ae821'
down_revision = '23d186979072'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    ### end Alembic commands ###
